### PR TITLE
introducing flag to decide whether to send confirmation email or welc…

### PR DESCRIPTION
**Pull request by szgooru**
…ome email. And encoding the token that is embedded in email templates

### CODE REVIEW

**Comment by am-gooru** [comment]
@szgooru, @gooru-subbu 

So, we are not planning to do anything with email status for the users who signed up during initial phases of 3.0? Is there any feature asking user to confirm email when this is not set up in FE?

**Comment by szgooru** [comment]
@am-gooru @gooru-subbu 

Yes, we are planning to display notice on Profile to non confirmed user and from there they can (re) send confirmation email.

**Comment by am-gooru** [comment]
There is no API where users can trigger confirmation email for themselves,
right?


--AM

**Comment by szgooru** [comment]
@am-gooru 
Yes there is API to resend confirmation email. https://github.com/Gooru/nucleus-auth-gateway/blob/master/api-docs/USER.MD#resend-confirmation-email

**Comment by am-gooru** [comment]
Ok.


--AM

**Pull request merged**
